//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVy
    {
        public string Title { get; set; }
        public string Ratings { get; set; }
        public string Summary { get; set; }
        public string Genre { get; set; }
    }
}
